name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: hrishabh1103
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
